name: CI
on:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v2
        with:
          toolchain: 1.78.0
          components: rustfmt, clippy
          override: true
      - name: rustfmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  tests:
    needs: linter
    strategy:
      matrix:
        toolchain:
          - 1.63
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v2
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      - name: tests
        run: cargo test --verbose --color always -- --nocapture
